version: '3.8'

services:
  backend:
    build:
      context: ./hack_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: development
    volumes:
      - ./hack_backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./hack_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_BASE_URL: "http://localhost:8000"
    volumes:
      - ./hack_frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped